# Data wrangling - La cirugía de datos

El **data wrangling**, a veces **data munging**, es el proceso de transformar y mapear datos de un *raw dataset* en otro formato con la intención de hacerlo más apropiado y valioso para una variedad de propósitos posteriores, como el análisis.

Esto puede incluir munging, visualización de datos, agregación de datos, entrenamiento de modelo estadístico, así como muchos otros usos potenciales. La oscilación de datos como proceso generalmente sigue un conjunto de pasos generales que comienzan extrayendo los datos crudos del origen de datos, dividiendo los datos en bruto usando algoritmos o analizando los datos en estructuras de datos preferidas, y, finalmente, depositando el contenido resultante en un sistema de almacenamiento (o silo) para su uso futuro.

In [1]:
# Importando todas las librerías
import pandas as pd
import numpy  as np
import os

In [2]:
mainpath = "/home/mauricio/anaconda_projects/datasets"
filename = "customer-churn-model/Customer Churn Model.txt"
fullpath = os.path.join(mainpath, filename)

In [3]:
data = pd.read_csv(fullpath)
data.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

## Crear un subconjunto de datos

In [4]:
account_length = data['Account Length'] # Ya no es dataframe, sino series
type(account_length)

pandas.core.series.Series

In [5]:
subset = data[['Account Length','Phone','Eve Charge','Day Calls']]
subset.head()

   Account Length     Phone  Eve Charge  Day Calls
0             128  382-4657       16.78        110
1             107  371-7191       16.62        123
2             137  358-1921       10.30        114
3              84  375-9999        5.26         71
4              75  330-6626       12.61        113

In [6]:
desired_columns = ["Account Length","Phone", "Eve Charge", "Day Calls"]
subset = data[desired_columns]
subset.head()

   Account Length     Phone  Eve Charge  Day Calls
0             128  382-4657       16.78        110
1             107  371-7191       16.62        123
2             137  358-1921       10.30        114
3              84  375-9999        5.26         71
4              75  330-6626       12.61        113

In [7]:
# Lista por bucle
sublist = []
not_desired = ['Account Length','Phone','Area Code']
for col in data.columns.values.tolist():
    if col not in not_desired:
        sublist.append(col)

In [8]:
# Lista por comprensión
sublist = [col for col in data.columns.values.tolist() if col not in not_desired]

In [9]:
# Lista por diferencia de conjuntos
sublist = list(set(data.columns.values)-set(not_desired))

In [10]:
subset = data[sublist]
subset.head()

,Night Calls,VMail Plan,CustServ Calls,Night Mins,Eve Calls,Eve Charge,Intl Charge,State,VMail Message,Day Charge,Int'l Plan,Intl Calls,Intl Mins,Eve Mins,Churn?,Day Calls,Night Charge,Day Mins
0,91,yes,1,244.7,99,16.78,2.70,KS,25,45.07,no,3,10.0,197.4,False.,110,11.01,265.1
1,103,yes,1,254.4,103,16.62,3.70,OH,26,27.47,no,3,13.7,195.5,False.,123,11.45,161.6
2,104,no,0,162.6,110,10.30,3.29,NJ,0,41.38,no,5,12.2,121.2,False.,114,7.32,243.4
3,89,no,2,196.9,88,5.26,1.78,OH,0,50.90,yes,7,6.6,61.9,False.,71,8.86,299.4
4,121,no,3,186.9,122,12.61,2.73,OK,0,28.34,yes,3,10.1,148.3,False.,113,8.41,166.7

In [11]:
data[10:10+5]

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
10,IN,65,415,329-6603,no,no,0,129.1,137,21.95,...,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True.
11,RI,74,415,344-9403,no,no,0,187.7,127,31.91,...,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False.
12,IA,168,408,363-1107,no,no,0,128.8,96,21.90,...,71,8.92,141.1,128,6.35,11.2,2,3.02,1,False.
13,MT,95,510,394-8006,no,no,0,156.6,88,26.62,...,75,21.05,192.3,115,8.65,12.3,5,3.32,3,False.
14,IA,62,415,366-9238,no,no,0,120.7,70,20.52,...,76,26.11,203.0,99,9.14,13.1,6,3.54,4,False.

In [12]:
data[:8] # Es lo mismo que data[0:8]

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.
5,AL,118,510,391-8027,yes,no,0,223.4,98,37.98,...,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False.
6,MA,121,510,355-9993,no,yes,24,218.2,88,37.09,...,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False.
7,MO,147,415,329-9001,yes,no,0,157.0,79,26.69,...,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False.

In [13]:
data[3320:]

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
3320,GA,122,510,411-5677,yes,no,0,140.0,101,23.80,...,77,16.69,120.1,133,5.40,9.7,4,2.62,4,True.
3321,VT,60,415,400-2738,no,no,0,193.9,118,32.96,...,110,7.23,210.1,134,9.45,13.2,8,3.56,3,False.
3322,MD,62,408,409-1856,no,no,0,321.1,105,54.59,...,122,22.57,180.5,72,8.12,11.5,2,3.11,4,True.
3323,IN,117,415,362-5899,no,no,0,118.4,126,20.13,...,97,21.19,227.0,56,10.22,13.6,3,3.67,5,True.
3324,WV,159,415,377-1164,no,no,0,169.8,114,28.87,...,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False.
3325,OH,78,408,368-8555,no,no,0,193.4,99,32.88,...,88,9.94,243.3,109,10.95,9.3,4,2.51,2,False.
3326,OH,96,415,347-6812,no,no,0,106.6,128,18.12,...,87,24.21,178.9,92,8.05,14.9,7,4.02,1,False.
3327,SC,79,415,348-3830,no,no,0,134.7,98,22.90,...,68,16.12,221.4,128,9.96,11.8,5,3.19,2,False.
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False.
3329,WV,68,415,370-3271,no,no,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False.
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False.
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False.
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False.

In [14]:
# Usuarios con Day Mins > 300
data1 = data[data['Day Mins'] > 300]
data1

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
15,NY,161,415,351-7269,no,no,0,332.9,67,56.59,...,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True.
76,DC,82,415,374-5353,no,no,0,300.3,109,51.05,...,100,15.39,270.1,73,12.15,11.7,4,3.16,0,True.
156,OH,83,415,370-9116,no,no,0,337.4,120,57.36,...,116,19.33,153.9,114,6.93,15.8,7,4.27,0,True.
197,TX,208,510,378-3625,no,no,0,326.5,67,55.51,...,113,14.99,181.7,102,8.18,10.7,6,2.89,2,True.
230,MD,93,408,360-3324,yes,no,0,312.0,109,53.04,...,100,11.00,217.6,74,9.79,10.5,2,2.84,0,True.
289,OK,89,510,352-6976,no,no,0,303.9,95,51.66,...,114,22.18,312.1,89,14.04,5.3,3,1.43,1,True.
365,CO,154,415,343-5709,no,no,0,350.8,75,59.64,...,94,18.40,253.9,100,11.43,10.1,9,2.73,1,True.
534,LA,67,510,373-6784,no,no,0,310.4,97,52.77,...,123,5.65,246.5,99,11.09,9.2,10,2.48,4,False.
575,SD,114,415,351-7369,no,yes,36,309.9,90,52.68,...,89,17.03,183.5,105,8.26,14.2,2,3.83,1,False.
605,MO,112,415,373-2053,no,no,0,335.5,77,57.04,...,109,18.06,265.0,132,11.93,12.7,8,3.43,2,True.
688,MN,13,510,338-7120,no,yes,21,315.6,105,53.65,...,71,17.76,260.1,123,11.70,12.1,3,3.27,3,False.
732,IN,48,510,342-6696,no,no,0,300.4,94,51.07,...,103,11.32,197.4,94,8.88,7.2,5,1.94,2,False.
815,KY,75,415,341-1191,no,no,0,314.6,102,53.48,...,86,14.43,285.1,100,12.83,5.7,3,1.54,2,True.
832,SC,87,408,335-1874,no,no,0,322.5,106,54.83,...,93,17.39,186.2,128,8.38,9.4,4,2.54,2,True.
901,CT,23,510,370-5527,no,no,0,321.6,107,54.67,...,115,21.39,141.1,158,6.35,11.3,3,3.05,2,True.
975,DE,129,510,332-6181,no,no,0,334.3,118,56.83,...,104,16.33,191.0,83,8.59,10.4,6,2.81,0,True.
985,NY,64,415,345-9140,yes,no,0,346.8,55,58.96,...,79,21.21,275.4,102,12.39,13.3,9,3.59,1,True.
1078,ME,80,408,333-7631,no,no,0,322.3,113,54.79,...,95,18.87,162.8,123,7.33,6.7,8,1.81,0,True.
1165,VT,50,415,387-5891,yes,yes,26,307.1,94,52.21,...,78,24.60,174.9,109,7.87,8.0,3,2.16,0,False.
1334,KS,126,408,379-8681,no,no,0,321.3,99,54.62,...,93,14.27,193.6,106,8.71,8.0,4,2.16,1,True.
1355,TX,50,408,330-6436,no,yes,31,302.7,93,51.46,...,119,20.44,193.9,103,8.73,13.6,14,3.67,3,False.
1679,OK,82,510,393-4823,no,no,0,329.8,73,56.07,...,120,17.71,267.1,102,12.02,10.6,6,2.86,0,True.
1830,CT,50,408,351-9037,no,no,0,301.7,82,51.29,...,118,14.20,72.2,89,3.25,10.5,6,2.84,1,False.
2028,SD,93,510,408-4836,no,no,0,328.1,106,55.78,...,89,12.89,303.5,114,13.66,8.7,3,2.35,1,True.
2215,MS,13,415,413-7468,no,no,0,303.2,133,51.54,...,86,14.49,227.6,80,10.24,11.5,3,3.11,0,True.
2259,NC,210,415,363-7802,no,yes,31,313.8,87,53.35,...,103,12.55,192.7,97,8.67,10.1,7,2.73,3,False.
2267,MS,29,510,401-6982,no,no,0,313.2,103,53.24,...,151,18.39,218.4,106,9.83,12.8,4,3.46,2,True.
2376,NV,42,415,352-5466,no,no,0,303.9,106,51.66,...,54,19.74,147.1,76,6.62,5.8,3,1.57,1,True.
2412,WI,89,415,373-4264,no,no,0,326.3,112,55.47,...,110,14.03,162.9,97,7.33,7.5,1,2.03,1,True.
2478,TN,123,415,415-3016,no,yes,34,305.2,80,51.88,...,109,13.30,280.0,81,12.60,13.2,7,3.56,1,False.
2572,MN,152,415,378-9542,no,no,0,317.8,60,54.03,...,100,13.00,123.4,63,5.55,10.4,7,2.81,1,True.
2573,WV,124,415,344-1970,no,no,0,312.0,112,53.04,...,109,15.30,168.6,94,7.59,12.8,4,3.46,1,True.
2594,OH,115,510,348-1163,yes,no,0,345.3,81,58.70,...,106,17.29,217.5,107,9.79,11.8,8,3.19,1,True.
2629,NH,141,415,402-3370,no,yes,32,322.4,92,54.81,...,107,24.07,209.5,111,9.43,6.7,3,1.81,1,True.
2660,NJ,88,415,347-8659,no,no,0,301.5,136,51.26,...,72,21.90,132.9,118,5.98,13.4,2,3.62,4,True.
2677,IA,44,415,359-7426,no,no,0,308.6,139,52.46,...,94,12.82,198.7,66,8.94,7.3,3,1.97,4,True.
2696,MI,74,415,359-6232,no,no,0,314.1,86,53.40,...,99,18.90,259.0,121,11.66,12.3,5,3.32,3,True.
2824,OR,81,415,406-4100,no,no,0,324.7,48,55.20,...,82,20.09,187.6,78,8.44,13.1,5,3.54,0,True.
2858,AL,141,510,388-8583,no,yes,28,308.0,123,52.36,...,128,21.06,152.9,103,6.88,7.4,3,2.00,1,False.
3072,TX,75,415,417-4456,no,no,0,305.1,106,51.87,...,115,15.98,235.4,116,10.59,8.5,5,2.30,0,True.
3132,NC,161,415,394-5489,no,no,0,322.3,100,54.79,...,135,19.58,241.5,104,10.87,7.8,5,2.11,2,True.
3207,DC,93,408,345-1994,no,yes,22,306.2,123,52.05,...,83,16.12,240.3,107,10.81,11.7,2,3.16,0,False.
3322,MD,62,408,409-1856,no,no,0,321.1,105,54.59,...,122,22.57,180.5,72,8.12,11.5,2,3.11,4,True.

In [15]:
# Usuarios de Nueva York (State = 'NY')
data2 = data[data['State'] == 'NY']

In [16]:
# Combinación de condiciones: &, |
data3 = data[(data['Day Mins'] > 300) & (data['State'] == 'NY')]
data3[['Day Mins','State']]

     Day Mins State
15      332.9    NY
985     346.8    NY

In [17]:
data4 = data[(data['Day Mins'] > 300) | (data['State'] == 'NY')]
data4[['Day Mins','State']]

      Day Mins State
15       332.9    NY
76       300.3    DC
77        61.6    NY
136      175.8    NY
156      337.4    OH
...        ...   ...
3227     153.7    NY
3257     137.5    NY
3275     128.5    NY
3310     190.4    NY
3322     321.1    MD

[124 rows x 2 columns]

In [18]:
data5 = data[(data['State'] == 'OH') & (data['Day Calls'] < data['Night Calls'])]
data5

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
362,OH,39,415,421-9752,no,yes,36,141.7,121,24.09,...,113,19.75,222.1,131,9.99,12.0,5,3.24,1,False.
404,OH,73,415,338-4065,no,no,0,183.4,80,31.18,...,115,20.57,201.4,100,9.06,7.5,3,2.03,4,False.
437,OH,100,510,385-8997,no,no,0,278.0,76,47.26,...,74,15.02,219.5,126,9.88,8.3,4,2.24,0,True.
462,OH,144,415,392-3813,no,yes,18,106.4,109,18.09,...,113,9.19,208.4,111,9.38,10.1,5,2.73,1,False.
506,OH,136,415,407-2248,no,yes,31,143.1,88,24.33,...,65,20.11,227.8,120,10.25,11.4,5,3.08,2,False.
599,OH,75,510,370-3021,no,yes,46,214.1,62,36.40,...,111,17.08,246.8,126,11.11,9.2,6,2.48,0,False.
808,OH,61,510,327-5525,yes,yes,16,143.5,76,24.40,...,58,20.62,147.7,95,6.65,11.3,3,3.05,0,False.
816,OH,83,510,342-9480,no,no,0,227.9,78,38.74,...,115,17.64,211.7,100,9.53,12.1,5,3.27,1,False.
930,OH,74,415,336-5661,no,no,0,136.7,106,23.24,...,105,19.43,265.3,114,11.94,9.8,4,2.65,0,False.
973,OH,137,408,328-2110,no,no,0,144.0,90,24.48,...,100,15.44,128.1,93,5.76,12.3,2,3.32,0,False.
1060,OH,124,510,362-1490,no,no,0,193.0,97,32.81,...,99,7.63,172.8,104,7.78,15.3,3,4.13,1,False.
1080,OH,114,415,363-2602,no,no,0,191.5,88,32.56,...,78,14.89,220.3,118,9.91,0.0,0,0.00,0,False.
1201,OH,119,415,359-5718,no,yes,35,217.1,92,36.91,...,134,18.77,249.5,93,11.23,8.0,5,2.16,2,False.
1389,OH,94,510,367-9495,no,no,0,194.1,62,33.00,...,54,19.31,190.4,115,8.57,15.3,4,4.13,1,False.
1418,OH,29,415,397-3058,yes,yes,37,235.0,101,39.95,...,79,15.58,139.8,106,6.29,5.7,7,1.54,2,False.
1468,OH,75,510,372-2296,no,yes,27,117.5,102,19.98,...,127,17.58,194.4,114,8.75,4.2,7,1.13,3,False.
1471,OH,75,415,340-9803,no,no,0,150.6,99,25.60,...,83,25.63,158.7,104,7.14,8.1,5,2.19,0,False.
1504,OH,65,510,351-8955,no,no,0,153.9,117,26.16,...,122,18.71,280.5,147,12.62,8.5,3,2.30,2,False.
1627,OH,29,408,402-6666,no,no,0,196.8,81,33.46,...,110,14.28,132.6,98,5.97,12.7,7,3.43,2,False.
1710,OH,146,415,358-3604,no,no,0,169.5,93,28.82,...,71,19.63,269.8,115,12.14,9.0,7,2.43,2,False.
1758,OH,134,408,355-6826,no,no,0,202.7,105,34.46,...,90,19.12,253.9,108,11.43,12.1,7,3.27,0,False.
1821,OH,123,408,396-6247,no,yes,39,270.4,99,45.97,...,110,20.83,108.9,113,4.90,15.4,7,4.16,1,False.
1831,OH,93,415,397-9184,no,yes,42,152.3,90,25.89,...,102,22.74,266.9,130,12.01,11.3,5,3.05,7,False.
1897,OH,86,415,356-3448,no,yes,29,225.4,79,38.32,...,112,15.90,281.1,112,12.65,12.9,3,3.48,1,False.
2048,OH,164,510,347-1263,no,yes,27,159.7,102,27.15,...,113,14.35,244.1,127,10.98,9.6,9,2.59,3,False.
2131,OH,52,408,327-9289,no,yes,31,142.1,77,24.16,...,97,16.41,253.4,88,11.40,11.0,4,2.97,1,False.
2141,OH,98,510,347-6393,no,yes,29,111.1,105,18.89,...,101,18.52,248.1,108,11.16,6.6,3,1.78,2,False.
2177,OH,109,415,363-4967,no,no,0,193.6,58,32.91,...,115,12.64,282.5,105,12.71,13.1,1,3.54,2,False.
2196,OH,132,415,375-5414,no,yes,10,182.9,54,31.09,...,68,24.85,142.3,116,6.40,11.5,4,3.11,0,False.
2224,OH,68,510,380-9990,no,no,0,143.6,80,24.41,...,65,11.42,215.6,84,9.70,15.5,5,4.19,2,False.
2251,OH,80,415,382-2453,no,no,0,197.6,83,33.59,...,86,13.98,94.0,98,4.23,6.4,6,1.73,1,False.
2471,OH,95,415,329-8056,no,yes,23,160.3,87,27.25,...,101,17.20,191.1,122,8.60,7.4,3,2.00,0,False.
2594,OH,115,510,348-1163,yes,no,0,345.3,81,58.70,...,106,17.29,217.5,107,9.79,11.8,8,3.19,1,True.
2904,OH,136,408,392-1547,yes,no,0,183.4,103,31.18,...,113,12.06,200.4,122,9.02,10.4,9,2.81,2,False.
2907,OH,165,510,378-8567,no,no,0,209.4,67,35.60,...,89,23.27,150.2,88,6.76,12.8,1,3.46,0,False.
2950,OH,133,408,380-4374,no,no,0,117.8,100,20.03,...,105,16.93,244.1,119,10.98,11.8,4,3.19,0,True.
2982,OH,87,510,350-5993,no,no,0,153.3,106,26.06,...,117,19.08,273.4,152,12.30,8.9,5,2.40,2,False.
3005,OH,66,415,408-6305,no,no,0,170.5,103,28.99,...,77,21.62,197.3,138,8.88,10.5,2,2.84,2,False.
3008,OH,32,415,401-6977,no,yes,31,232.8,97,39.58,...,111,15.60,206.8,111,9.31,13.0,2,3.51,0,False.
3209,OH,68,415,369-8574,yes,yes,24,125.7,92,21.37,...,98,23.45,214.5,108,9.65,14.2,6,3.83,3,True.
3249,OH,160,415,337-9326,no,no,0,206.3,66,35.07,...,109,20.49,227.8,102,10.25,11.7,6,3.16,0,False.
3251,OH,88,408,354-3040,no,no,0,274.6,105,46.68,...,121,13.69,194.4,123,8.75,9.2,4,2.48,2,False.
3325,OH,78,408,368-8555,no,no,0,193.4,99,32.88,...,88,9.94,243.3,109,10.95,9.3,4,2.51,2,False.

In [20]:
## Minutos de día, noche y longitud de la cuenta, primeros 50 individuos
desired = ['Day Mins', 'Night Mins', 'Account Length']
subset_first_50 = data[desired][:50] # ¡Se puede hacer dos en uno!

In [21]:
# El .ix es una propiedad para Python2. Ahora, se usa loc
data.iloc[0:10, 3:6] # iloc con 'i' de índice
data.iloc[:,3:6] # Todas las filas para las columnas de 3 a 6
data.iloc[:100, :] #Todas las columnas para las primeras 100 filas
data.iloc[[0,2,3,8,10], [2,5,7]] # Para diferentes columnas no consecutivas

    Area Code VMail Plan  Day Mins
0         415        yes     265.1
2         415         no     243.4
3         408         no     299.4
8         408         no     184.5
10        415         no     129.1

In [48]:
data.loc[[0,1,5,8,36],['Area Code','Day Mins']] # loc para etiquetas, no posición

    Area Code  Day Mins
0         415     265.1
1         415     161.6
5         510     223.4
8         408     184.5
36        408     146.3

## Añadir columna nueva

In [51]:
data['Total Mins'] = data['Day Mins'] + data['Night Mins'] + data['Eve Mins']
data['Total Mins'].head()

0    707.2
1    611.5
2    527.2
3    558.2
4    501.9
Name: Total Mins, dtype: float64

In [52]:
data['Total Calls'] = data['Day Calls'] + data['Night Calls'] + data['Eve Calls']
data['Total Calls'].head()

0    300
1    329
2    328
3    248
4    356
Name: Total Calls, dtype: int64

## Generación de números aleatorios

Realmente, no son del todo números aleatorios, sino pseudo aleatorios. La cosa es que se repite cada *mucho tiempo*. Permite realizar simulaciones ,para generar *dummy datasets* o para realizar un muestreo.

In [68]:
# Generar un número aleatorio entre 1 y 100
np.random.randint(1,100)

40

In [69]:
# Forma más clásica de generar un número aleatorio entre 0 y 1
np.random.random()

0.2740850329711716

In [74]:
# Generar lista de n números aleatorios dentro del intervalo [a,b]
def randint_list(n, a, b):
    x = []
    for i in range(n):
        x.append(np.random.randint(a,b))
    return x

In [87]:
randint_list(25,0,10)

[4, 7, 8, 9, 8, 0, 8, 7, 3, 6, 4, 1, 9, 2, 1, 3, 8, 1, 6, 8, 4, 6, 2, 3, 9]

In [90]:
np.random.randint(0,10,25).tolist()

[8, 6, 7, 8, 9, 8, 9, 6, 5, 0, 2, 0, 1, 3, 9, 9, 8, 3, 1, 4, 1, 9, 2, 5, 8]

In [91]:
import random

In [121]:
for i in range(5):
    a = random.randrange(0, 100, 11)
    if  a % 11 == 0:
        print('Divisible:', a)
    else:
        print('No divisible: ', a)

Divisible: 99
Divisible: 66
Divisible: 22
Divisible: 99
Divisible: 11

In [126]:
def try_useless(n, a, b, d):
    for i in range(n):
        x = random.randrange(a, b, d)
        if x % d == 0:
            print('Divisible by',d,':',x)
        else:
            print('Not divisible by',d,':',x)

In [133]:
try_useless(5, 0, 100, 5)

Divisible by 5 : 95
Divisible by 5 : 45
Divisible by 5 : 65
Divisible by 5 : 55
Divisible by 5 : 65

### Shuffling

In [136]:
a = np.arange(100) # Mezcla entre array y range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [141]:
np.random.shuffle(a) # Ahora, 'a' está mezclado.
a

array([17, 71, 23,  9, 64, 12, 87, 80, 61, 39, 69, 89, 65, 13, 72,  6, 14,
       28, 81, 21, 63, 86, 19, 83, 84, 55, 31, 44, 29, 96, 70, 82, 27,  7,
        5, 24, 53, 57, 73, 60, 32, 40, 20, 76, 18, 47, 45, 11, 95, 62, 34,
       50, 91, 37, 90,  2, 67,  1, 15, 59, 52,  0, 33, 85, 99, 22, 77, 30,
       10, 35, 68, 51, 36, 26, 79,  4, 75, 46, 16, 66, 78, 97, 56, 41, 38,
       74,  3, 43, 94, 98,  8, 58, 48, 25, 42, 93, 92, 54, 88, 49])

In [146]:
column_list = data.columns.values.tolist()

### Choice

In [160]:
np.random.choice(column_list, 4).tolist()

['Night Calls', 'Day Mins', 'Total Mins', 'Night Calls']

### Seed

Es un número que se utiliza para dar el valor inicial a los números aleatorios. Permite la reproducción del experimento.

In [174]:
np.random.seed(2018) # ¡Establecer la semilla al inicio!
for i in range(5):
    print(np.random.random())

0.8823493117539459
0.10432773786047767
0.9070093335163405
0.3063988986063515
0.446408872427422